title: Muddy Card Study Resources
description: Collection of resources to assist teachers in particpating in the muddy card study.
theme: just-the-docs

url: https://tjelton.github.io/Muddy-Card-Study-Resources/

